name: Rust

env:
  rust_version: "stable"

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/rust.yml'
      - 'src/**/*.rs'
      - 'tests/**/*.rs'
      - 'Cargo.toml'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - '**'
    paths:
      - '.github/workflows/rust.yml'
      - 'src/**/*.rs'
      - 'tests/**/*.rs'
      - 'Cargo.toml'

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust Unix
      if: runner.os != 'Windows'
      run: |
        if rustup --version >/dev/null 2>&1; then
            rustup install ${{ env.rust_version }}
            rustup default ${{ env.rust_version }}
        else
            curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal --default-toolchain ${{ env.rust_version }}
            echo ::add-path::$HOME/.cargo/bin
        fi
    - name: Install Rust Windows
      if: runner.os == 'Windows'
      run: |
        if (Get-Command "rustup" -ErrorAction SilentlyContinue) {
            rustup install ${{ env.rust_version }}
            rustup default ${{ env.rust_version }}
        } else {
            Invoke-WebRequest https://static.rust-lang.org/rustup/dist/i686-pc-windows-gnu/rustup-init.exe -OutFile rustup-init.exe
            ./rustup-init.exe -y --profile minimal --default-toolchain ${{ env.rust_version }}
            echo ::add-path::%USERPROFILE%\.cargo\bin
        }

    - name: Rust version
      run: |
        cargo --version
        rustc --version

    - name: Install Valgrind
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y valgrind

    - name: Check WASM
      run: |
        rustup target add wasm32-unknown-unknown
        cargo check --target wasm32-unknown-unknown

    - name: Test
      run: cargo test --tests

    - name: Valgrind Test
      if: runner.os == 'Linux'
      env:
        CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER: "valgrind --leak-check=full --error-exitcode=1"
      run: cargo test --release
