name: Rust

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/rust.yml'
      - 'src/**/*.rs'
      - 'tests/**/*.rs'
      - 'Cargo.toml'
      - 'valgrind.supp'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - '**'
    paths:
      - '.github/workflows/rust.yml'
      - 'src/**/*.rs'
      - 'tests/**/*.rs'
      - 'Cargo.toml'
      - 'valgrind.supp'

jobs:
  check:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    if: github.event.pull_request.draft == false
    uses: DoumanAsh/douman-ci/.github/workflows/rust.yml@master
    with:
      runs-on: ${{ matrix.os }}
      cargo-no-features: true
      cargo-features: "std"
      valgrind: true
      valgrind_flags: "--suppressions=valgrind.supp"

  wasm-platform-test:
    needs: [check]
    if: github.event.pull_request.draft == false
    uses: DoumanAsh/douman-ci/.github/workflows/wasm-rust.yml@master

  cross-platform-test:
    needs: [check]
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        target: [
          "arm-unknown-linux-musleabi",
          "i586-unknown-linux-musl",
          "powerpc-unknown-linux-gnu",
          "aarch64-unknown-linux-musl",
          # Current cross cannot link libunwind
          # https://github.com/cross-rs/cross/issues/1222
          #"aarch64-linux-android",
        ]

    uses: DoumanAsh/douman-ci/.github/workflows/cross-rust.yml@master
    with:
      cargo-target: ${{ matrix.target }}
